server:
  port: 8080
spring:
#    유레카 서버에 아래 application.name으로 서비스를 등록.
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: item-service
#        lb://application.name(유레카에 등록된 서비스명이 들어온다)
#        uri: http:localhost:8081으로 선언하면 로드밸런싱이 아니라 8081로 직접 연결
          uri: lb://item-service
#        /item-service로 시작하는 url 요청이 들어올 경우
          predicates:
            - Path=/item-service/**
#         filters의 StripPrefix=1은 첫번째 접두어 제거
          filters:
            - StripPrefix=1
        - id: member-service
          uri: lb://member-service
          predicates:
            - Path=/member-service/**
          filters:
            - StripPrefix=1
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order-service/**
          filters:
            - StripPrefix=1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
jwt:
  expiration:  30  #30분
  secretKey: mysecret
#  instance:
#    preferIpAddress: true
#    hostname: localhost
