server:
  port: 8081
spring:
  security:
    user:
      name: user
      password: password #PasswordEncoder.encode(password)
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/ordering_spring
    username: root
    password: 1234
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show_sql: true
jwt:
  expiration:  30  #30분
  secretKey: mysecret